/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spaw;

/**
 *
 * @author Sagar
 */
public class Order extends javax.swing.JFrame {

    /**
     * Creates new form Ordpage
     */
    public Order() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        dateLabel = new javax.swing.JLabel();
        addItemButton = new javax.swing.JButton();
        displayDate = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        mobileLabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        searchBox = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        addressText = new javax.swing.JTextField();
        mobileText = new javax.swing.JTextField();
        cityText = new javax.swing.JTextField();
        nextButton = new javax.swing.JButton();
        selectDropdown = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dateLabel.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        dateLabel.setText("Date");
        getContentPane().add(dateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(704, 20, 30, 20));

        addItemButton.setText("addItem");
        addItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addItemButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 15, -1, -1));

        displayDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayDateActionPerformed(evt);
            }
        });
        getContentPane().add(displayDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 73, -1));

        nameLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        nameLabel.setText("Name");
        getContentPane().add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, 20));

        addressLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        addressLabel.setText("Address");
        getContentPane().add(addressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        cityLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        cityLabel.setText("City");
        getContentPane().add(cityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        mobileLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        mobileLabel.setText("Mobile");
        getContentPane().add(mobileLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });
        getContentPane().add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 300, -1));

        searchBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchBoxKeyPressed(evt);
            }
        });
        getContentPane().add(searchBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 15, 156, 23));

        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, ""},
                {null, null, null, null, null}
            },
            new String [] {
                "Sr. No.", "Model Name", "Model Type", "QTY", "Rate"
            }
        ));
        jScrollPane2.setViewportView(orderTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 110, 780, 188));

        addressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTextActionPerformed(evt);
            }
        });
        getContentPane().add(addressText, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 300, -1));

        mobileText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileTextActionPerformed(evt);
            }
        });
        getContentPane().add(mobileText, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 300, -1));
        getContentPane().add(cityText, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 300, -1));

        nextButton.setLabel("NEXT");
        getContentPane().add(nextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 520, -1, -1));

        selectDropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Cash", "Cheqe" }));
        selectDropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectDropdownActionPerformed(evt);
            }
        });
        getContentPane().add(selectDropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 90, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextActionPerformed

    private void addressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTextActionPerformed

    private void mobileTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileTextActionPerformed

    private void searchBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchBoxKeyPressed
        // TODO add your handling code here
        
    }//GEN-LAST:event_searchBoxKeyPressed

    private void displayDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayDateActionPerformed

    private void addItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addItemButtonActionPerformed

    private void selectDropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectDropdownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectDropdownActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItemButton;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressText;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityText;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField displayDate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel mobileLabel;
    private javax.swing.JTextField mobileText;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameText;
    private javax.swing.JButton nextButton;
    private javax.swing.JTable orderTable;
    private javax.swing.JTextField searchBox;
    private javax.swing.JComboBox<String> selectDropdown;
    // End of variables declaration//GEN-END:variables
}
